name: generate rule

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate RuleSets
        run: |
          chmod +x generate_rules.sh
          ./generate_rules.sh

      - name: Deploy to release branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release
          publish_dir: ./ruleset_txt
          force_orphan: true
          commit_message: "🔄 Auto update rulesets"
          enable_jekyll: true 
